// Generated by CoffeeScript 1.6.3
test('get rss from url', function() {
  var url;
  url = Reader.get_rss('techcrunch.com');
  return ok(1, 'Rss retriving result:' + url);
});

asyncTest('get feeds', function() {
  var url;
  url = Reader.get_rss('techcrunch.com');
  return Reader.get_feeds(url, function(data) {
    console.log('back now');
    ok(true, 'feeds get ' + data.items.length + ' items');
    return start();
  });
});

asyncTest('get icon', function() {
  return Reader.get_icon('http://techcrunch.com', function(icon) {
    ok(true, 'icon retrived: ' + icon);
    return start();
  });
});
